input:
  slnName:
    description: "The name of the solution file"
    required: true
  platform:
    description: "The path to the image file to use to run the build process"
    required: true
  filePath:
    description: "The path to the files to be included in the artifact"
    required: true
  artifactName:
    description: "The name to give the produced artifact"
    required: true
  extraFileScript:
    description: "Any pipe operations you want to perform on the contents of the directory located at 'filePath'. Note: must begin with a space and then a pipe character."
    required: false
  imageMods:
    description: "A yaml file with operations to perform on the target platform before building"
    required: false

jobs:
  build:        
    runs-on: ${{ platform }}

    ${{ imageMods }}

    env:
      Solution_Name: '${{ slnName }}.sln'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ artifactName }}
          path: ${{ filePath }}${{ extraFileScript }}
          
  zip:
    uses: jjerhub/Utilites.GithubActions/ZipContents
    with:
      name: ${{ artifactName }}
