on:
  release:
    types:
      - created
inputs:
  name:
    description: "The name to give the zip file"
    required: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Zip
        run: zip -r {{$name}}.zip . -x "*.git*"
        
      - name: Amend release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: {{$name}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
