on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Zip
        run: zip -r ADRFDR_Extended.zip . -x "*.git*"
        
      - name: Amend release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ADRFDR_Extended.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
