name: Make Railloader mod zip
on:
  workflow_dispatch:
    inputs:
      mod-name:
        type: string
        description: 'The name of the mod'
        required: true
      zip-file-name:
        type: string
        description: 'The name to give the zip file'
        required: false
      from-file-filter:
        type: string
        description: 'The URI for files to copy to the new destination'
        default: . -x "*.git*" "gitignore*"
      to-file-filter:
        type: string
        description: 'The URI for where to put the copied files'
        required: false
  workflow_call:
    inputs:
      mod-name:
        type: string
        description: 'The name of the mod'
        required: true
      zip-file-name:
        type: string
        description: 'The name to give the zip file'
        required: false
      from-file-filter:
        type: string
        description: 'The URI for files to copy to the new destination'
        default: . -x "*.git*" "gitignore*"
      to-file-filter:
        type: string
        description: 'The URI for where to put the copied files'
        required: false

permissions:
  contents:
    write
jobs:
  do_copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Copy and zip
        env:
          FROM_FILE_FILTER: ${{ inputs.from-file-filter }}
          TO_FILE_FILTER: ${{ inputs.to-file-filter }}
          ZIP_FILE_NAME: ${{ inputs.zip-file-name }}
          MOD_NAME: ${{ inputs.mod-name }}
        run: |
          eval '${TO_FILE_FILTER:=Mods/'${MOD_NAME}'}'
          eval '${ZIP_FILE_NAME:='${MOD_NAME}'}'
          eval 'cp '${FROM_FILE_FILTER}' '${TO_FILE_FILTER}
          eval 'zip -r '${ZIP_FILE_NAME}'.zip Mods'
      - name: Amend release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ inputs.zip-file-name || inputs.mod-name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
